variables:
    GIT_STRATEGY: clone

stages:
    - test

before_script:

ClangFormatCheck:
  stage: test
  image: bce7edfda510
  script:
  - ROOT_DIR_TRANSLATOR=`pwd`
  - cd translator/include/xbyak_translator_for_aarch64/instructions
  - ../../../tools/init_variables.sh
  - ../../../tools/replace_preg_name.sh
  - cd ${ROOT_DIR_TRANSLATOR}
  - pwd
  - ./.github/automation/clang-format.sh

ClangFormatCheck:
  stage: test
  image: 677b25a35be8
  script:
  - ./.github/automation/clang-format.sh

job_1:
  stage: test
  image: bce7edfda510
  script:
#    - pwd
#    - ls
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - cd translator/third_party/
    - mkdir build_xed_aarch64
    - cd build_xed_aarch64/
    - ../xed/mfile.py --host-cpu=aarch64 --shared examples install
    - cd kits/
    - XED=`ls | grep install`
    - ln -sf $XED xed
    - cd xed/bin/
    - CI_XED_PATH=`pwd`
    - cd ../../../../../
    - source dot.zshrc.xbyak.ci
    - cd tests/
    - make -j46
#  tags: 
#    - instruction_unit 
